import io
import logging
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable, KeepTogether
)

logger = logging.getLogger("uvicorn")

MEDICAL_DISCLAIMER_TEXT = (
    "DISCLAIMER: MedBrief is an AI-assisted clinical information summary tool designed to assist "
    "healthcare professionals and patients in digesting medical documents. MedBrief DOES NOT provide "
    "medical advice, official diagnosis, or treatment recommendations. Always consult a qualified "
    "healthcare professional for clinical decision-making."
)

def generate_pdf_report(summary_data: dict) -> bytes:
    """
    Generates a clean, professional PDF summary document from structured report data.

    Args:
        summary_data (dict): Complete structured summary dictionary containing patient info,
                             clinical sections, lab results table, and text summaries.

    Returns:
        bytes: Binary PDF file content.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=0.5 * inch,
        leftMargin=0.5 * inch,
        topMargin=0.5 * inch,
        bottomMargin=0.5 * inch
    )

    styles = getSampleStyleSheet()

    # Custom typography styles
    title_style = ParagraphStyle(
        'ReportTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=20,
        leading=24,
        textColor=colors.HexColor('#1e3a8a'), # Navy blue
        spaceAfter=4
    )

    subtitle_style = ParagraphStyle(
        'ReportSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=12,
        textColor=colors.HexColor('#475569'),
        spaceAfter=12
    )

    section_heading_style = ParagraphStyle(
        'SectionHeading',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=13,
        leading=16,
        textColor=colors.HexColor('#0f172a'),
        spaceBefore=10,
        spaceAfter=6
    )

    body_style = ParagraphStyle(
        'BodyTextCustom',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#334155'),
        spaceAfter=6
    )

    label_style = ParagraphStyle(
        'LabelStyle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#1e293b')
    )

    disclaimer_style = ParagraphStyle(
        'DisclaimerStyle',
        parent=styles['Normal'],
        fontName='Helvetica-Oblique',
        fontSize=8,
        leading=11,
        textColor=colors.HexColor('#64748b')
    )

    story = []

    # 1. Header & Title
    story.append(Paragraph("MedBrief — Clinical Summary Report", title_style))
    story.append(Paragraph("Generated by MedBrief AI Clinical Summarization Pipeline", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#2563eb'), spaceAfter=12))

    # 2. Patient Demographics Box
    patient_info = summary_data.get("patient_information", {})
    patient_name = patient_info.get("patient_name", "Not mentioned")
    age = patient_info.get("age", "N/A")
    gender = patient_info.get("gender", "N/A")
    report_date = patient_info.get("report_date", patient_info.get("date_of_visit", "N/A"))

    demo_data = [
        [
            Paragraph("<b>Patient Name:</b> " + str(patient_name), body_style),
            Paragraph("<b>Age:</b> " + str(age), body_style)
        ],
        [
            Paragraph("<b>Gender:</b> " + str(gender), body_style),
            Paragraph("<b>Report Date:</b> " + str(report_date), body_style)
        ]
    ]

    demo_table = Table(demo_data, colWidths=[3.75 * inch, 3.75 * inch])
    demo_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#f8fafc')),
        ('BOX', (0, 0), (-1, -1), 1, colors.HexColor('#e2e8f0')),
        ('PADDING', (0, 0), (-1, -1), 8),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    story.append(demo_table)
    story.append(Spacer(1, 12))

    # Helper function to get text content from section object or string
    def _get_sec_content(sec):
        if isinstance(sec, dict):
            return sec.get("content", "Not mentioned")
        return str(sec) if sec else "Not mentioned"

    # 3. Abstractive & Extractive Summaries
    abs_summary = summary_data.get("abstractive_summary_text", "")
    ext_summary = summary_data.get("extractive_summary_text", "")

    if abs_summary:
        story.append(Paragraph("Abstractive AI Summary", section_heading_style))
        story.append(Paragraph(abs_summary, body_style))
        story.append(Spacer(1, 8))

    if ext_summary:
        story.append(Paragraph("Extractive Key Sentences", section_heading_style))
        story.append(Paragraph(ext_summary, body_style))
        story.append(Spacer(1, 10))

    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor('#cbd5e1'), spaceAfter=10))

    # 4. Extracted Clinical Findings
    story.append(Paragraph("Extracted Clinical Findings", section_heading_style))

    clinical_sections = [
        ("Symptoms & Concerns", summary_data.get("symptoms")),
        ("Diagnosis & Conditions", summary_data.get("diagnosis_conditions")),
        ("Prescribed Medications", summary_data.get("medications")),
        ("Diagnostic Procedures", summary_data.get("procedures")),
        ("Follow-up Directives", summary_data.get("follow_up")),
        ("Other Observations", summary_data.get("other_observations")),
    ]

    for sec_title, sec_val in clinical_sections:
        content_text = _get_sec_content(sec_val)
        story.append(Paragraph(f"<b>{sec_title}:</b> {content_text}", body_style))

    story.append(Spacer(1, 10))

    # 5. Laboratory Findings & Vitals Table
    lab_table_rows = summary_data.get("lab_results_table", [])
    if lab_table_rows and len(lab_table_rows) > 0:
        story.append(Paragraph("Laboratory Findings & Vitals", section_heading_style))
        
        table_data = [
            [
                Paragraph("<b>Test Name</b>", label_style),
                Paragraph("<b>Result</b>", label_style),
                Paragraph("<b>Unit</b>", label_style),
                Paragraph("<b>Reference Range</b>", label_style),
                Paragraph("<b>Flag</b>", label_style),
            ]
        ]

        for row in lab_table_rows:
            flag_val = row.get("flag", "Normal")
            flag_color = "#dc2626" if flag_val == "High" else ("#2563eb" if flag_val == "Low" else "#16a34a")
            flag_text = f"<font color='{flag_color}'><b>{flag_val}</b></font>"

            table_data.append([
                Paragraph(row.get("test_name", ""), body_style),
                Paragraph(str(row.get("result", "")), body_style),
                Paragraph(row.get("unit", "-") or "-", body_style),
                Paragraph(row.get("reference_range", "-") or "-", body_style),
                Paragraph(flag_text, body_style),
            ])

        lab_table = Table(table_data, colWidths=[2.2 * inch, 1.1 * inch, 1.1 * inch, 1.9 * inch, 1.2 * inch])
        lab_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#f1f5f9')),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 6),
            ('TOPPADDING', (0, 0), (-1, 0), 6),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cbd5e1')),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('PADDING', (0, 0), (-1, -1), 5),
        ]))
        story.append(lab_table)
        story.append(Spacer(1, 12))
    else:
        lab_findings_sec = _get_sec_content(summary_data.get("lab_findings"))
        story.append(Paragraph(f"<b>Laboratory Findings & Vitals:</b> {lab_findings_sec}", body_style))
        story.append(Spacer(1, 12))

    # 6. Medical Disclaimer Footer Box
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#94a3b8'), spaceAfter=10))
    disclaimer_box = Table([[Paragraph(MEDICAL_DISCLAIMER_TEXT, disclaimer_style)]], colWidths=[7.5 * inch])
    disclaimer_box.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#f8fafc')),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#cbd5e1')),
        ('PADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(disclaimer_box)

    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()
